package com.leetcode.bit;

/**
 * @author wcl
 * @date 5:15 PM 2020/4/23
 * <a href="https://leetcode.com/problems/find-the-difference/">
 *     Find the Difference</a>
 * @see MissingNumber
 */
public class FindTheDifference {
    /**
     * Given two strings s and t which consist of only lowercase letters.
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     *
     * Find the letter that was added in t.
     *
     * Example:
     *
     * Input:
     * s = "abcd"
     * t = "abcde"
     *
     * Output:
     * e
     *
     * Explanation:
     * 'e' is the letter that was added.
     */
    public static char findTheDifference(String s, String t) {
        if(s == null || s.length() == 0) {
            return t.charAt(0);
        }
        char res = s.charAt(0);
        for (int i = 1; i < s.length(); i++) {
            res ^= s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            res ^= t.charAt(i);
        }
        return res;
    }

    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd", "abcdf"));
    }
}
